spring:
  application:
    name: SpringWebAnnotation
  servlet:
    multipart:
      location: D://
  mvc:
    problemdetails:
      enabled: true
  banner:
    charset: utf-8
    location: static/banner.txt


logging:
  level:
    web: debug

product:
  books:
    - isbn: B001
      name: java
      author: zhangsan
    - isbn: B002
      name: python
      author: lisi
    - isbn: B003
      name: javascript
      author: wangwu
